2018-05-19 18:15:06,369 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:45]
2018-05-19 18:16:02,681 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:45]
2018-05-19 18:17:18,361 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:45]
2018-05-20 12:23:45,435 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:46]
2018-05-20 12:24:12,498 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 12:25:40,669 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 12:27:26,127 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 12:29:06,072 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 12:30:02,039 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 12:32:44,580 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 12:35:46,077 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 12:36:52,993 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 12:38:08,067 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 15:27:49,664 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 15:48:08,677 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 15:49:46,198 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 15:50:33,677 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 15:53:08,063 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 15:55:38,534 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 15:56:36,817 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:47]
2018-05-20 16:26:36,781 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:49]
2018-05-20 16:27:47,647 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:49]
2018-05-20 16:29:08,895 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:49]
2018-05-20 16:31:22,625 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:49]
2018-05-20 16:31:59,240 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:49]
2018-05-20 16:40:07,752 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-20 16:57:00,889 ERROR: Exception on /register [POST] [in /home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shigaki/microblog/app/routes.py", line 70, in register
    db.session.commit()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username [SQL: u'INSERT INTO user (username, email, password_hash, about_me, last_seen) VALUES (?, ?, ?, ?, ?)'] [parameters: (u'shigaki', u'dada@co.jp', 'pbkdf2:sha256:50000$EM2DE06R$034fddcc10ab4877525b9e9546911b74a11b8f2803779122f2366a5327dfcf5f', None, '2018-05-20 07:57:00.889520')] (Background on this error at: http://sqlalche.me/e/gkpj)
2018-05-20 16:58:21,564 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
