2018-05-22 13:42:53,538 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-22 13:45:37,827 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-22 13:45:47,943 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-22 16:06:45,122 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-22 16:06:53,544 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-22 16:07:00,762 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-22 18:57:00,338 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-22 18:58:35,171 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-22 18:59:05,002 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-22 19:00:02,953 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-22 19:00:45,634 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-22 19:00:52,004 ERROR: Exception on /index [GET] [in /home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/shigaki/microblog/app/routes.py", line 47, in index
    prev_url=prev_url)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shigaki/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/shigaki/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/shigaki/microblog/app/templates/base.html", line 23, in block "navbar"
    <li><a href="{{ url_for('news') }}">News</a></li>
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'news'. Did you mean 'index' instead?
2018-05-22 19:00:52,382 ERROR: Exception on /favicon.ico [GET] [in /home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/home/shigaki/microblog/app/errors.py", line 7, in not_found_error
    return render_template('404.html'), 404
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shigaki/microblog/app/templates/404.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/shigaki/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/shigaki/microblog/app/templates/base.html", line 23, in block "navbar"
    <li><a href="{{ url_for('news') }}">News</a></li>
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'news'. Did you mean 'index' instead?
2018-05-22 19:01:28,447 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-22 19:04:55,195 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
